### ISSUE TITLE
pod install . help me

### ISSUE THREAD

**Issue by tindang** [advaita13/YouTubeFloatingPlayer#12]
i install but error 
[!] Unable to find a specification for `YouTubeFloatingPlayer`

code podfile 

> # Uncomment this line to define a global platform for your project
> # platform :ios, '9.0'
> target 'mytarget' do
>   # Comment this line if you're not using Swift and don't want to use dynamic frameworks
>   use_frameworks!
> pod 'YouTubeFloatingPlayer'
>   
> end

please help me! thank you

**Comment by advaita13** [comment]
Did you specify the source at the top of your Podfile?

`source 'https://github.com/CocoaPods/Specs.git'`
